CREATE TABLE carros (
  id BIGINT AUTO_INCREMENT NOT NULL,
   nome VARCHAR(255) NOT NULL,
   marca VARCHAR(255) NOT NULL,
   modelo VARCHAR(255) NOT NULL,
   foto LONGTEXT NULL,
   CONSTRAINT pk_carros PRIMARY KEY (id)
);